const colormaps = [
  { name: 'reds', type: 'sequentialSingleHue' },
  { name: 'oranges', type: 'sequentialSingleHue' },
  { name: 'yellows', type: 'sequentialSingleHue' },
  { name: 'greens', type: 'sequentialSingleHue' },
  { name: 'teals', type: 'sequentialSingleHue' },
  { name: 'blues', type: 'sequentialSingleHue' },
  { name: 'purples', type: 'sequentialSingleHue' },
  { name: 'pinks', type: 'sequentialSingleHue' },
  { name: 'greys', type: 'sequentialSingleHue' },
  { name: 'fire', type: 'sequentialMultiHue' },
  { name: 'earth', type: 'sequentialMultiHue' },
  { name: 'water', type: 'sequentialMultiHue' },
  { name: 'heart', type: 'sequentialMultiHue' },
  { name: 'wind', type: 'sequentialMultiHue' },
  { name: 'warm', type: 'sequentialMultiHue' },
  { name: 'cool', type: 'sequentialMultiHue' },
  { name: 'pinkgreen', type: 'diverging' },
  { name: 'redteal', type: 'diverging' },
  { name: 'orangeblue', type: 'diverging' },
  { name: 'yellowpurple', type: 'diverging' },
  { name: 'redgrey', type: 'diverging' },
  { name: 'orangegrey', type: 'diverging' },
  { name: 'yellowgrey', type: 'diverging' },
  { name: 'greengrey', type: 'diverging' },
  { name: 'tealgrey', type: 'diverging' },
  { name: 'bluegrey', type: 'diverging' },
  { name: 'purplegrey', type: 'diverging' },
  { name: 'pinkgrey', type: 'diverging' },
  { name: 'rainbow', type: 'cyclical' },
  { name: 'sinebow', type: 'cyclical' },
]

export default colormaps